name: Micro UI

env:
  "PULUMI_STACK_NAME": igoran/infra-micro-ui/dev

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout unshallow
      with:
        fetch-depth: 0
    - name: Pulumi - Setup CLI
      run: |
        curl https://get.pulumi.com | bash
        echo "::add-path::$HOME/.pulumi/bin/"
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    - name: Pulumi - Provisioning Azure Cloud Resources
      working-directory: ./infra
      run: |
        pulumi stack select ${{ env.PULUMI_STACK_NAME }} --non-interactive --create
        pulumi config set azure:location westeurope
        pulumi config set azure:clientId ${{ secrets.AZURE_CLIENT_ID }} 
        pulumi config set azure:clientSecret ${{ secrets.AZURE_SECRET }} --secret  
        pulumi config set azure:tenantId ${{ secrets.AZURE_TENANT_ID }}  
        pulumi config set azure:subscriptionId ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        pulumi up --non-interactive --yes
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}